Move tests to root and refactor pipeline

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,27 +9,13 @@ on:
   pull_request:
 
 jobs:
+  lint:
+    name: Lint
+    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v32.0.0
+
   build:
-    name: Build Snap
-    runs-on: ubuntu-latest
-    timeout-minutes: 60
-    outputs:
-      snap-file: ${{ steps.build-snap.outputs.snap }}
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - id: build-snap
-        name: Build snap
-        uses: snapcore/action-build@v1
-
-      - name: Upload built snap job artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: cassandra_snap_amd64
-          path: "cassandra_*.snap"
+    name: Build snap
+    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v32.0.0
 
   test:
     name: Test Snap
@@ -42,7 +28,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      
+
       - name: Install required dependencies
         run: |
           sudo snap install yq
@@ -56,8 +42,7 @@ jobs:
       - name: Install snap file
         run: |
           version="$(cat snap/snapcraft.yaml | yq .version)"
-          
-          sudo snap remove --purge cassandra
+          sudo snap remove --purge cassandra || true
           sudo snap install cassandra_${version}_amd64.snap --dangerous --devmode
 
       - name: Connect required interfaces
@@ -72,36 +57,30 @@ jobs:
       - name: Setup and Start Cassandra
         run: |
           sudo snap run cassandra.setup
-  
-          # start cassnadra
           sudo snap start cassandra.daemon
-
-          # wait a bit for it to fully initialize
           sleep 240s
 
       - name: Ensure the cluster is reachable and node created via tests
         run: |
-             set -e
-             sudo snap run cassandra.test-node-status
-     
+          set -e
+          bash tests/test-node-status.sh
+
       - name: Upgrade snap
         run: |
           version="$(cat snap/snapcraft.yaml | yq .version)"
           sudo snap install cassandra_${version}_amd64.snap --dangerous --devmode
 
-          if [ "$(ls /var/snap/cassandra/x2)" ]; then
+          if [ -d /var/snap/cassandra/x2 ]; then
               echo "Snap upgraded."
           else
+              echo "Snap upgrade check failed: x2 revision directory not found."
               exit 1
           fi
 
-          # start cassnadra
           sudo snap start cassandra.daemon
-
-          # wait a bit for it to fully initialize
           sleep 240s
 
       - name: Ensure the cluster is reachable and node created after upgrade
         run: |
-             set -e
-             sudo snap run cassandra.test-node-status
+          set -e
+          bash tests/test-node-status.sh
